import { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import { CgChevronLeft, CgChevronRight } from 'react-icons/cg';
import NavMenu from '../components/navMenu';
import VideoCard from '../components/videoCard';
import { getAmbassadorer } from '../lib/api';

type PageProps = {
    ambassadorer: Array<any>;
};

const Home: NextPage = ({ ambassadorer }: PageProps) => {
    const [current, setCurrent] = useState(0);
    const length = ambassadorer.length;

    const nextSlide = () => {
        setCurrent(current === length - 1 ? 0 : current + 1);
    };

    const prevSlide = () => {
        setCurrent(current === 0 ? length - 1 : current - 1);
    };

    return (
        <>
            <Head>
                <title>Stand Velgskog</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <NavMenu />

            <section className="slider mobile">
                <div className="left-arrow">
                    <CgChevronLeft className="left-icon" onClick={prevSlide} />
                </div>
                <div className="right-arrow">
                    <CgChevronRight
                        className="right-icon"
                        onClick={nextSlide}
                    />
                </div>

                <div className="card-grid container">
                    {ambassadorer.map(({ node }, index) => {
                        return (
                            <div
                                className={
                                    index === current ? 'slide active' : 'slide'
                                }
                                key={index}
                            >
                                {index === current && (
                                    <VideoCard key={node.id} item={node} />
                                )}
                            </div>
                        );
                    })}
                </div>
            </section>

            <div className="__inner bg desktop">
                <div className="image-background">
                    <Image
                        src="/bakgrunn-2.jpg"
                        alt="Picture of the author"
                        width={3936}
                        height={2624}
                    />
                </div>
                <div className="card-grid container">
                    {ambassadorer.map(({ node }, i) => {
                        return <VideoCard key={i} item={node} />;
                    })}
                </div>
            </div>

            <section className="container">
                <span className="button-wrapper">
                    <a href="https://www.nhomd.no/velgskog">
                        <button className="btn center">
                            Tilbake til forsiden
                        </button>
                    </a>
                </span>
            </section>
        </>
    );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
    const ambassadorer = await getAmbassadorer();

    return {
        props: {
            ambassadorer,
        },
    };
};
