import Head from "next/head";
import Image from "next/image";
import Footer from "../components/Footer";
import NavMenu from "../components/NavMenu";
import Layout from "../components/Layout";
import { getAmbassadorer, getFrontPageAcf, getFooterAcf } from "../lib/api";

export default function Home({ ambassadorer, frontPage, footerAcf }) {
    return (
        <>
            <div>
                <Head>
                    <title>Stand velg skog</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
            </div>
            <NavMenu />

            <Layout data={frontPage.frontpageAcf} ambassadorer={ambassadorer} />

            <Footer data={footerAcf.footerAcf} />
        </>
    );
}

export async function getStaticProps() {
    const ambassadorer = await getAmbassadorer();
    const frontPage = await getFrontPageAcf();
    const footerAcf = await getFooterAcf();

    return {
        props: {
            ambassadorer,
            frontPage,
            footerAcf
        }
    };
}
